version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest   # Postgres with pgvector pre-installed (ARM works fine on M1)
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:



